export const images = {
  deliverIcon:
    'https://storage.googleapis.com/collect-your-shopping-landingpage/Icon-Deliver.svg',
  albertHeijin:
    'https://storage.googleapis.com/collect-your-shopping-landingpage/albertheijnLogo.svg',
  android:
    'https://storage.googleapis.com/collect-your-shopping-landingpage/android.svg',
  appMobilePhysical:
    'https://storage.googleapis.com/collect-your-shopping-landingpage/app-mobile-phys.png',
  appMobile:
    'https://storage.googleapis.com/collect-your-shopping-landingpage/app-mobile.png',
  apple:
    'https://storage.googleapis.com/collect-your-shopping-landingpage/apple.svg',
  cnLogo:
    'https://storage.googleapis.com/collect-your-shopping-landingpage/cnLogo.png',
  convenience:
    'https://storage.googleapis.com/collect-your-shopping-landingpage/convenience.png',
  basket:
    'https://storage.googleapis.com/collect-your-shopping-landingpage/convenience.svg',
  cysLogo:
    'https://storage.googleapis.com/collect-your-shopping-landingpage/CYS-updated-bigger-logo.png',
  cysTextLogo:
    'https://storage.googleapis.com/collect-your-shopping-landingpage/cys2.png',
  deliveryGuy:
    'https://storage.googleapis.com/collect-your-shopping-landingpage/deliver.png',
  earn: 'https://storage.googleapis.com/collect-your-shopping-landingpage/earn.svg',
  ekoplazaLogo:
    'https://storage.googleapis.com/collect-your-shopping-landingpage/ekoplazaLogo.png',
  faqs: 'https://storage.googleapis.com/collect-your-shopping-landingpage/faq.jpg',
  google:
    'https://storage.googleapis.com/collect-your-shopping-landingpage/google.svg',
  kauflandLogo:
    'https://storage.googleapis.com/collect-your-shopping-landingpage/kauflandLogo.png',
  lidlLogo:
    'https://storage.googleapis.com/collect-your-shopping-landingpage/lidlLogo.png',
  phoneFrame:
    'https://storage.googleapis.com/collect-your-shopping-landingpage/phone-frame.svg',
  product:
    'https://storage.googleapis.com/collect-your-shopping-landingpage/product.svg',
  qrCode:
    'https://storage.googleapis.com/collect-your-shopping-landingpage/qr-code.svg',
  reweLogo:
    'https://storage.googleapis.com/collect-your-shopping-landingpage/reweLogo.png',
  smileBox:
    'https://storage.googleapis.com/collect-your-shopping-landingpage/smilebox.png',
  tescoLogo:
    'https://storage.googleapis.com/collect-your-shopping-landingpage/tescoLogo.png',
  user: 'https://storage.googleapis.com/collect-your-shopping-landingpage/customer.png',
  variety:
    'https://storage.googleapis.com/collect-your-shopping-landingpage/variety.svg',
  deliverIcon:
    'https://storage.googleapis.com/collect-your-shopping-landingpage/deliver-icon.svg',
  cysValues:
    'https://storage.googleapis.com/collect-your-shopping-landingpage/CYS-Values.mp4',
  cysValuesGif:
    'https://storage.googleapis.com/collect-your-shopping-landingpage/CYS-Values.gif',
  adventurous:
    'https://storage.googleapis.com/collect-your-shopping-landingpage/Adventurous.png',
  inclusive:
    'https://storage.googleapis.com/collect-your-shopping-landingpage/Inclusive.png',
  positive:
    'https://storage.googleapis.com/collect-your-shopping-landingpage/Positive.png',
  responsible:
    'https://storage.googleapis.com/collect-your-shopping-landingpage/Responsible.png',
  sustainable:
    'https://storage.googleapis.com/collect-your-shopping-landingpage/Sustainable.png',
  innovative:
    'https://storage.googleapis.com/collect-your-shopping-landingpage/Innovative.svg',
}
